# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bvoc5/CRYSTALS_NTT/Dilithium_R2_CT_NTT/Dilithium_R2_CT_NTT.srcs/sources_1/ip/c_add_0_1/c_add_0.xci
# IP: The module: 'c_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bvoc5/CRYSTALS_NTT/Dilithium_R2_CT_NTT/Dilithium_R2_CT_NTT.gen/sources_1/ip/c_add_0_1/c_add_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/bvoc5/CRYSTALS_NTT/Dilithium_R2_CT_NTT/Dilithium_R2_CT_NTT.srcs/sources_1/ip/c_add_0_1/c_add_0.xci
# IP: The module: 'c_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bvoc5/CRYSTALS_NTT/Dilithium_R2_CT_NTT/Dilithium_R2_CT_NTT.gen/sources_1/ip/c_add_0_1/c_add_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
